# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69a67c97ae1aa6e94706f90ef788811c3aef3f4ad1d9d6e2160795a85ce49f2e9b14656bf30961d613047ba025d81ec126e9e484b47081ab1a02d883d2484d95

test:
  secret_key_base: ff6da5f7513d49e122e1e0f1613faec252dd5583b209d96535c2c30f229d9e6617d4d02ac5ddc5d6352f0eb76aaf932d6458c88b7a3d4328e0c2bd1ac99bb7b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
